#image: microsoft/dotnet:latest
#image: microsoft/dotnet-framework
image: mono:latest

#before_script:
#  - git submodule sync --recursive
#  - git submodule update --init --recursive

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
#  - echo "Restoring NuGet packages..."
#  - nuget restore "./projects/GEDKeeper2.linux.sln"
  - echo "Starting build..."
  - 'msbuild /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /p:Configuration=Debug /p:CIMode=true /p:MonoCS=true /verbosity:quiet "./projects/GEDKeeper2.linux.sln"'
  artifacts:
    expire_in: 1 week
    untracked: true
  only:
    - master

test_job:
  stage: test
  script:
  - echo "Starting tests..."
  - 'nunit-console ./projects/GKTests/bin/Debug/GKTests.dll'
  artifacts:
    expire_in: 1 week
  dependencies:
    - build_job

deploy_job:
  stage: deploy
  script:
  - echo "Starting deploy..."
  dependencies:
    - build_job
    - test_job
