language: csharp
solution: projects/GEDKeeper2.linux.sln

after_success:
  - cd projects
  - ./generateCoverageConfig.sh > ./coverageConfig.json
  - mono ./packages/SharpCover/SharpCover.exe instrument ./coverageConfig.json
  - mono ./packages/SharpCover/SharpCover.exe check
  - bash <(curl -s https://codecov.io/bash)

install:
  - sudo apt-get install nunit-console
  - nuget restore ./projects/GEDKeeper2.linux.sln
 
script:
  - xbuild /p:Configuration=Debug ./projects/GEDKeeper2.linux.sln
  - nunit-console ./projects/GKTests/bin/Debug/GKTests.dll
