language: csharp
solution: projects/GEDKeeper2.linux.sln

after_success:
  - bash <(curl -s https://codecov.io/bash)

install:
  - sudo apt-get install nunit-console
  - nuget restore ./projects/GEDKeeper2.linux.sln
 
script:
  - xbuild /p:Configuration=Release ./projects/GEDKeeper2.linux.sln
  - nunit-console ./projects/GKTests/bin/Release/GKTests.dll